# Generated by Django 2.0.13 on 2020-09-22 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200922_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingadress',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Order'),
        ),
    ]
