# Generated by Django 2.0.13 on 2020-11-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201102_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default=1, upload_to='Profile'),
            preserve_default=False,
        ),
    ]
